# Site
name: "River Pairs"
title_suffix: "River Pairs"
title: "River Pairs"
description: "River Pairs"
meta_description: "River Pairs"
logo: "/assets/images/riverpairs.png"
favicon: "/assets/images/favicon.ico"
baseurl: "https://www.riverpairs.com"
permalink: /:title
email: ""
google_analytics: ""
future: true

# Authors
authors:
  reece:
    name: Reece
    display_name: Reece Williams 
    gravatar:
    email: ""
    description: ""
